# imagen base alpine con openssh  
image: alpine/ssh-client:1.0

# busca dentro del repositorio los archivos con extencion {.bar}, si hay mas de uno toma el primero
before_script:
  - cd $CI_PROJECT_NAME
  - export BarFileName=`find -iname '*.bar' | head -1`

# IntegrationServer: nombre del IS donde se quiere hacer el deploy
variables:
    IntegrationServer: "MultiMisc"

# Lista de las etapas que se ejecutaran durante el proceso
# verify: Verifica la existencia del Integration Server
# send: Envia el archivo .bar a los servidores IIB
# deploy: Ejecuta el comando mqsideploy tomando el archivo .bar
# clean: elimina el archivo .bar del servidor

stages:
  - verify
  - send
  - deploy
  - clean

# proceso para devl ref al branch master
verify_devl:
  stage: verify
  script:
    - ssh -oHostKeyAlgorithms=+ssh-dss -i ~/.ssh/id_rsa -T mqbrkrs@devl028ms06.itesm.mx /home/mqbrkrs/CI_CD/scripts/checkIS.sh $IntegrationServer
  only:
    refs:
      - master
    changes:
      - "**/*.bar"
sendBarFile_devl:
  stage: send
  script:
    - scp -oHostKeyAlgorithms=+ssh-dss -i ~/.ssh/id_rsa -r $BarFileName mqbrkrs@devl028ms06.itesm.mx:/home/mqbrkrs/CI_CD/deployBars
  only:
    refs:
      - master
  needs: ["verify_devl"]
deploy_devl:
  stage: deploy
  script:
    - ssh -oHostKeyAlgorithms=+ssh-dss -i ~/.ssh/id_rsa -T mqbrkrs@devl028ms06.itesm.mx /home/mqbrkrs/CI_CD/scripts/runDeploy.sh $BarFileName $IntegrationServer
  only:
    refs:
      - master
  needs: ["sendBarFile_devl"]
clean_devl:
  stage: clean
  script:
    - ssh -oHostKeyAlgorithms=+ssh-dss -i ~/.ssh/id_rsa -T mqbrkrs@devl028ms06.itesm.mx /home/mqbrkrs/CI_CD/scripts/cleanAll.sh $BarFileName
  only:
    refs:
      - master
  needs: ["deploy_devl"]

# proceso para pprd
verify_pprd:
  stage: verify
  script:
    - ssh -oHostKeyAlgorithms=+ssh-dss -i ~/.ssh/id_rsa -T mqbrkrs@pprd028ms12.itesm.mx /home/mqbrkrs/CI_CD/scripts/checkIS.sh $IntegrationServer
  only:
    refs:
      - pprd
    changes:
      - "**/*.bar"
sendBarFile_pprd:
  stage: send
  script:
    - scp -oHostKeyAlgorithms=+ssh-dss -i ~/.ssh/id_rsa -r $BarFileName mqbrkrs@pprd028ms12.itesm.mx:/home/mqbrkrs/CI_CD/deployBars
  only:
    refs:
      - pprd
  needs: ["verify_pprd"]
deploy_pprd:
  stage: deploy
  script:
    - ssh -oHostKeyAlgorithms=+ssh-dss -i ~/.ssh/id_rsa -T mqbrkrs@pprd028ms12.itesm.mx /home/mqbrkrs/CI_CD/scripts/runDeploy.sh $BarFileName $IntegrationServer
  only:
    refs:
      - pprd
  needs: ["sendBarFile_pprd"]
clean_pprd:
  stage: clean
  script:
    - ssh -oHostKeyAlgorithms=+ssh-dss -i ~/.ssh/id_rsa -T mqbrkrs@pprd028ms12.itesm.mx /home/mqbrkrs/CI_CD/scripts/cleanAll.sh $BarFileName
  only:
    refs:
      - pprd
  needs: ["deploy_pprd"]

# proceso para prod

# proceso para prod alestra
# nodo A
verify_NodeA:
  stage: verify
  script:
    - ssh -i ~/.ssh/id_rsa -T iibadmin@prod028ms28.itesm.mx /home/iibadmin/CI_CD/scripts/checkIS.sh $IntegrationServer
  only:
    refs:
      - prod-alestra
    changes:
      - "**/*.bar"
sendBarFile_NodeA:
  stage: send
  script:
    - scp -i ~/.ssh/id_rsa -r $BarFileName iibadmin@prod028ms28.itesm.mx:/home/iibadmin/CI_CD/deployBars
  only:
    refs:
      - prod-alestra
  needs: ["verify_NodeA"] 
deploy_NodeA:
  stage: deploy
  script:
    - ssh -i ~/.ssh/id_rsa -T iibadmin@prod028ms28.itesm.mx /home/iibadmin/CI_CD/scripts/runDeploy.sh $BarFileName $IntegrationServer
  only:
    refs:
      - prod-alestra
  needs: ["sendBarFile_NodeA"]
clean_NodeA:
  stage: clean
  script:
    - ssh -i ~/.ssh/id_rsa -T iibadmin@prod028ms28.itesm.mx /home/iibadmin/CI_CD/scripts/cleanAll.sh $BarFileName
  only:
    refs:
      - prod-alestra

# nodo B
verify_NodeB:
  stage: verify
  script:
    - ssh -i ~/.ssh/id_rsa -T iibadmin@prod028ms29.itesm.mx /home/iibadmin/CI_CD/scripts/checkIS.sh $IntegrationServer
  only:
    refs:
      - prod-alestra
    changes:
      - "**/*.bar"
sendBarFile_NodeB:
  stage: send
  script:
    - scp -i ~/.ssh/id_rsa -r $BarFileName iibadmin@prod028ms29.itesm.mx:/home/iibadmin/CI_CD/deployBars
  only:
    refs:
      - prod-alestra
  needs: ["verify_NodeB"]
deploy_NodeB:
  stage: deploy
  script:
    - ssh -i ~/.ssh/id_rsa -T iibadmin@prod028ms29.itesm.mx /home/iibadmin/CI_CD/scripts/runDeploy.sh $BarFileName $IntegrationServer
  only:
    refs:
      - prod-alestra
  needs: ["sendBarFile_NodeB"]
clean_NodeB:
  stage: clean
  script:
    - ssh -i ~/.ssh/id_rsa -T iibadmin@prod028ms29.itesm.mx /home/iibadmin/CI_CD/scripts/cleanAll.sh $BarFileName
  only:
    refs:
      - prod-alestra
